// ============================================================
// Antigravity Skill Pack Manifests — Phase 1 static baseline
// EPISTEMIC TIER: T2 · Gate 130
// Source: github.com/sickn33/antigravity-awesome-skills
//         (install via: npx antigravity-awesome-skills --claude)
// These 24 inputs represent constitutional translations of the
// Antigravity 58-skill aggregator into AEGIS SkillRecord format.
// Full catalog installed at runtime via the npx command above.
// ============================================================

import type { SkillInput } from '../types.js'

const BASE_DATE = '2026-01-01T00:00:00Z'

export const ANTIGRAVITY_SKILL_INPUTS: readonly SkillInput[] = [
  {
    skill_id: 'ag_git_workflow',
    name: 'git-workflow',
    confidence: 0.91,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['version-control', 'collaboration'],
    dependencies: [],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T1',
    primitive_mapping: 'SEQUENCE',
  },
  {
    skill_id: 'ag_code_review',
    name: 'code-review',
    confidence: 0.88,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['quality', 'governance'],
    dependencies: [],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T1',
    primitive_mapping: 'VERIFY',
  },
  {
    skill_id: 'ag_test_driven',
    name: 'test-driven-development',
    confidence: 0.85,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['testing', 'quality'],
    dependencies: [],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T1',
    primitive_mapping: 'VERIFY',
  },
  {
    skill_id: 'ag_api_design',
    name: 'api-design',
    confidence: 0.82,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['api', 'architecture'],
    dependencies: [],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'CANONICALIZE',
  },
  {
    skill_id: 'ag_refactoring',
    name: 'refactoring',
    confidence: 0.80,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['code-quality', 'architecture'],
    dependencies: ['ag_code_review'],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'CANONICALIZE',
  },
  {
    skill_id: 'ag_debugging',
    name: 'debugging',
    confidence: 0.87,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['debugging', 'diagnostics'],
    dependencies: [],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T1',
    primitive_mapping: 'VERIFY',
  },
  {
    skill_id: 'ag_documentation',
    name: 'documentation-writing',
    confidence: 0.79,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['documentation', 'communication'],
    dependencies: [],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'CANONICALIZE',
  },
  {
    skill_id: 'ag_ci_cd',
    name: 'ci-cd-pipeline',
    confidence: 0.84,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['deployment', 'automation'],
    dependencies: ['ag_test_driven'],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T1',
    primitive_mapping: 'SEQUENCE',
  },
  {
    skill_id: 'ag_security_audit',
    name: 'security-audit',
    confidence: 0.86,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['security', 'audit'],
    dependencies: [],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T1',
    primitive_mapping: 'VERIFY',
  },
  {
    skill_id: 'ag_performance_opt',
    name: 'performance-optimization',
    confidence: 0.77,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['performance', 'optimization'],
    dependencies: ['ag_debugging'],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'SEQUENCE',
  },
  {
    skill_id: 'ag_typescript_mastery',
    name: 'typescript-mastery',
    confidence: 0.90,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['typescript', 'type-safety'],
    dependencies: [],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T1',
    primitive_mapping: 'FREEZE',
  },
  {
    skill_id: 'ag_react_patterns',
    name: 'react-patterns',
    confidence: 0.83,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['frontend', 'react'],
    dependencies: ['ag_typescript_mastery'],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T1',
    primitive_mapping: 'CANONICALIZE',
  },
  {
    skill_id: 'ag_database_design',
    name: 'database-design',
    confidence: 0.81,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['database', 'architecture'],
    dependencies: [],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'HASH',
  },
  {
    skill_id: 'ag_system_design',
    name: 'system-design',
    confidence: 0.76,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['architecture', 'design'],
    dependencies: [],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'CANONICALIZE',
  },
  {
    skill_id: 'ag_ui_ux',
    name: 'ui-ux-design',
    confidence: 0.78,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['design', 'ux'],
    dependencies: [],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'CANONICALIZE',
  },
  {
    skill_id: 'ag_monitoring',
    name: 'observability-monitoring',
    confidence: 0.83,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['monitoring', 'operations'],
    dependencies: ['ag_ci_cd'],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T1',
    primitive_mapping: 'SEQUENCE',
  },
  {
    skill_id: 'ag_prompt_engineering',
    name: 'prompt-engineering',
    confidence: 0.75,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['ai', 'language-models'],
    dependencies: [],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'CANONICALIZE',
  },
  {
    skill_id: 'ag_agent_orchestration',
    name: 'agent-orchestration',
    confidence: 0.72,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['ai', 'orchestration'],
    dependencies: ['ag_prompt_engineering'],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'SEQUENCE',
  },
  {
    skill_id: 'ag_data_pipeline',
    name: 'data-pipeline',
    confidence: 0.80,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['data', 'automation'],
    dependencies: [],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'SEQUENCE',
  },
  {
    skill_id: 'ag_content_strategy',
    name: 'content-strategy',
    confidence: 0.73,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['content', 'marketing'],
    dependencies: [],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'CANONICALIZE',
  },
  {
    skill_id: 'ag_workflow_automation',
    name: 'workflow-automation',
    confidence: 0.81,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['automation', 'workflow'],
    dependencies: ['ag_ci_cd'],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'SEQUENCE',
  },
  {
    skill_id: 'ag_knowledge_management',
    name: 'knowledge-management',
    confidence: 0.76,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['knowledge', 'documentation'],
    dependencies: ['ag_documentation'],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'HASH',
  },
  {
    skill_id: 'ag_error_handling',
    name: 'error-handling',
    confidence: 0.85,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['reliability', 'quality'],
    dependencies: ['ag_debugging'],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T1',
    primitive_mapping: 'VERIFY',
  },
  {
    skill_id: 'ag_code_generation',
    name: 'code-generation',
    confidence: 0.74,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['code-generation', 'ai'],
    dependencies: ['ag_typescript_mastery', 'ag_prompt_engineering'],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'CANONICALIZE',
  },
] as const
