// ============================================================
// Core Agent Skill Manifests — Phase 1 static baseline
// EPISTEMIC TIER: T2 · Gate 130
// Maps 8 original + 7 CRGM AgentTypes to SkillInput records.
// These are static human-authored baselines; runtime telemetry
// updates them via SKILL_VALIDATED / SKILL_REINFORCED events.
// ============================================================

import type { SkillInput } from '../types.js'

const BASE_DATE = '2026-01-01T00:00:00Z'

export const CORE_AGENT_SKILL_INPUTS: readonly SkillInput[] = [
  {
    skill_id: 'workspace_mapping',
    name: 'workspace-mapping',
    confidence: 0.85,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['topology', 'mapping'],
    dependencies: [],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T1',
    primitive_mapping: 'CANONICALIZE',
  },
  {
    skill_id: 'research_synthesis',
    name: 'research-synthesis',
    confidence: 0.78,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['research', 'analysis'],
    dependencies: [],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T1',
    primitive_mapping: 'HASH',
  },
  {
    skill_id: 'replay_audit',
    name: 'replay-audit',
    confidence: 0.95,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['audit', 'replay', 'governance'],
    dependencies: [],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T0',
    primitive_mapping: 'VERIFY',
  },
  {
    skill_id: 'telemetry_analysis',
    name: 'telemetry-analysis',
    confidence: 0.82,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['telemetry', 'monitoring'],
    dependencies: [],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T1',
    primitive_mapping: 'SEQUENCE',
  },
  {
    skill_id: 'extension_governance',
    name: 'extension-governance',
    confidence: 0.88,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['governance', 'policy'],
    dependencies: ['replay_audit'],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T1',
    primitive_mapping: 'VERIFY',
  },
  {
    skill_id: 'invariant_enforcement',
    name: 'invariant-enforcement',
    confidence: 0.92,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['constitutional', 'enforcement'],
    dependencies: ['replay_audit'],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T0',
    primitive_mapping: 'FREEZE',
  },
  {
    skill_id: 'documentation_synthesis',
    name: 'documentation-synthesis',
    confidence: 0.75,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['documentation', 'knowledge'],
    dependencies: [],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'CANONICALIZE',
  },
  {
    skill_id: 'environment_adaptation',
    name: 'environment-adaptation',
    confidence: 0.72,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['adaptation', 'runtime'],
    dependencies: ['telemetry_analysis'],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'SEQUENCE',
  },
  // CRGM §8 — 7 new agent types (Gate 143 will add them to AgentType union)
  {
    skill_id: 'sentinel_detection',
    name: 'sentinel-detection',
    confidence: 0.80,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['security', 'threat-detection'],
    dependencies: ['invariant_enforcement'],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'VERIFY',
  },
  {
    skill_id: 'arbitration_validation',
    name: 'arbitration-validation',
    confidence: 0.83,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['governance', 'validation'],
    dependencies: ['replay_audit'],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'VERIFY',
  },
  {
    skill_id: 'memory_preservation',
    name: 'memory-preservation',
    confidence: 0.87,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['lineage', 'memory'],
    dependencies: ['replay_audit'],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'HASH',
  },
  {
    skill_id: 'entropy_suppression',
    name: 'entropy-suppression',
    confidence: 0.79,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['entropy', 'stability'],
    dependencies: ['invariant_enforcement'],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'FREEZE',
  },
  {
    skill_id: 'constitutional_guardian',
    name: 'constitutional-guardian',
    confidence: 0.90,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['constitutional', 'governance'],
    dependencies: ['invariant_enforcement', 'replay_audit'],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'VERIFY',
  },
  {
    skill_id: 'federation_relay',
    name: 'federation-relay',
    confidence: 0.70,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['federation', 'network'],
    dependencies: ['replay_audit'],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'SEQUENCE',
  },
  {
    skill_id: 'simulation_projection',
    name: 'simulation-projection',
    confidence: 0.65,
    validated_runs: 0,
    failure_rate: 0.0,
    recency_score: 1.0,
    domain_affinity: ['simulation', 'projection'],
    dependencies: ['telemetry_analysis'],
    evidence_refs: [],
    last_validated: BASE_DATE,
    epistemic_tier: 'T2',
    primitive_mapping: 'SEQUENCE',
  },
] as const
