class_name GameStateSingleton
extends Node
## Global Data Store for Kael's attributes and current world state across SYSTEM_REBUILD.

# --- Core Stats ---
## Vitality integrity. Act I (gritty stone) -> Act III (light-infused metal).
var current_health: float = 100.0 : set = set_current_health
var max_health: float = 100.0 : set = set_max_health

## Mental tension level [0.0, 1.0]. Fills during overthinking (boss fights); high tension causes damage/glitches.
var static_meter: float = 0.0 : set = set_static_meter

## Mental capacity. Used for cognitive abilities (System Cascade, Emotional Scan). Restored via parries & Inner Sanctum.
var mental_mana: float = 100.0 : set = set_mental_mana
var max_mental_mana: float = 100.0 : set = set_max_mental_mana

## Narrative progression & resilience [0.0, 1.0]. High resonance unlocks endings/bonuses.
var emotional_resonance: float = 0.0 : set = set_emotional_resonance

# --- Progression Stats ---
## Stacks built via consistency. Reduces static meter fill rate (5% per stack, max 50%). Partially persists death.
var behavioral_integrity: int = 0 : set = set_behavioral_integrity
const MAX_BEHAVIORAL_INTEGRITY: int = 10

## Tracks successful hits/actions in a row (e.g. for C2 Consistency Loop). Misses reset this.
var consistency_streak: int = 0 : set = set_consistency_streak

# --- Dialogue State ---
## True when NPC dialogue is active — blocks player movement input
var in_dialogue: bool = false

# --- Ability Unlocks (Skill Tree) ---
## Branch A1: Pattern Recognition — shows 1.5s intent trails on enemies (3.5s with Pocket Watch)
var pattern_recognition_active: bool = true  # Default true for dev/testing
## Duration override (Pocket Watch legendary sets this to 3.5)
var intent_trail_duration: float = 1.5

# --- World State ---
## Act I (Maze), Act II (Medical/Bureau), Act III (Ouroboros).
var current_act: int = 1

## E.g., "maze_of_thorns", "medical_bridge", "bureau_rigid_logic", "ouroboros_core".
var current_stage: String = "maze_of_thorns"

# --- Setters & Signaling ---
func set_current_health(value: float) -> void:
    var clamped: float = clamp(value, 0.0, max_health)
    if clamped != current_health:
        current_health = clamped
        EventBus.emit_signal("state_changed", "current_health", current_health)
        if current_health <= 0:
            GameManager.on_player_defeated()

func set_max_health(value: float) -> void:
    var new_max: float = max(1.0, value)
    if new_max != max_health:
        max_health = new_max
        EventBus.emit_signal("state_changed", "max_health", max_health)
        if current_health > max_health:
            current_health = max_health
func set_mental_mana(value: float) -> void:
    var clamped: float = clamp(value, 0.0, max_mental_mana)
    if clamped != mental_mana:
        mental_mana = clamped
        EventBus.emit_signal("state_changed", "mental_mana", mental_mana)

func set_max_mental_mana(value: float) -> void:
    var new_max: float = max(1.0, value)
    if new_max != max_mental_mana:
        max_mental_mana = new_max
        EventBus.emit_signal("state_changed", "max_mental_mana", max_mental_mana)
        if mental_mana > max_mental_mana:
            mental_mana = max_mental_mana

func set_static_meter(value: float) -> void:
    var clamped: float = clamp(value, 0.0, 1.0)
    if clamped != static_meter:
        static_meter = clamped
        EventBus.emit_signal("state_changed", "static_meter", static_meter)

func set_emotional_resonance(value: float) -> void:
    var clamped: float = clamp(value, 0.0, 1.0)
    if clamped != emotional_resonance:
        emotional_resonance = clamped
        EventBus.emit_signal("state_changed", "emotional_resonance", emotional_resonance)

func set_behavioral_integrity(value: int) -> void:
    var clamped: int = clampi(value, 0, MAX_BEHAVIORAL_INTEGRITY)
    if clamped != behavioral_integrity:
        behavioral_integrity = clamped
        EventBus.emit_signal("state_changed", "behavioral_integrity", behavioral_integrity)

func set_consistency_streak(value: int) -> void:
    var clamped: int = maxi(0, value)
    if clamped != consistency_streak:
        consistency_streak = clamped
        EventBus.emit_signal("state_changed", "consistency_streak", consistency_streak)

## Converts current state to Dictionary for SaveSystem.
func serialize() -> Dictionary:
    return {
        "current_health": current_health,
        "max_health": max_health,
        "static_meter": static_meter,
        "mental_mana": mental_mana,
        "max_mental_mana": max_mental_mana,
        "emotional_resonance": emotional_resonance,
        "behavioral_integrity": behavioral_integrity,
        "consistency_streak": consistency_streak,
        "current_act": current_act,
        "current_stage": current_stage,
        "pattern_recognition_active": pattern_recognition_active,
        "intent_trail_duration": intent_trail_duration
    }

## Loads state from a Dictionary generated by serialize().
func deserialize(data: Dictionary) -> void:
    if data.has("max_health"): max_health = data["max_health"]
    if data.has("current_health"): current_health = data["current_health"]
    if data.has("max_mental_mana"): max_mental_mana = data["max_mental_mana"]
    if data.has("static_meter"): static_meter = data["static_meter"]
    if data.has("mental_mana"): mental_mana = data["mental_mana"]
    if data.has("emotional_resonance"): emotional_resonance = data["emotional_resonance"]
    if data.has("behavioral_integrity"): behavioral_integrity = data["behavioral_integrity"]
    if data.has("consistency_streak"): consistency_streak = data["consistency_streak"]
    if data.has("current_act"): current_act = data["current_act"]
    if data.has("current_stage"): current_stage = data["current_stage"]
    if data.has("pattern_recognition_active"): pattern_recognition_active = data["pattern_recognition_active"]
    if data.has("intent_trail_duration"): intent_trail_duration = data["intent_trail_duration"]
